cmake_minimum_required(VERSION 3.23)

add_subdirectory(atomic)
add_subdirectory(block_buffer)
add_subdirectory(byte_streams)
add_subdirectory(cast)
add_subdirectory(chonk)
add_subdirectory(chrono)
add_subdirectory(command_options)
add_subdirectory(csv)
add_subdirectory(debugging)
add_subdirectory(error_handling)
add_subdirectory(filesystem)
add_subdirectory(googletest)
add_subdirectory(io)
add_subdirectory(math)
add_subdirectory(memory)
add_subdirectory(pe)
add_subdirectory(pil)
add_subdirectory(random)
add_subdirectory(rfc3339_clock)
add_subdirectory(rust-ffi-helpers)
add_subdirectory(strings)
add_subdirectory(thread_description)
add_subdirectory(threadpool)
add_subdirectory(tracing)
add_subdirectory(utf)

# this is by itself because it's a group of libraries
# not a single library. no good cause.

add_subdirectory(Platform-Adaptive)

set(m_installation_targets ${m_installation_targets} PARENT_SCOPE)
